# Generated by Django 5.2.4 on 2025-07-17 12:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('vente', 'Vendre'), ('location', 'Louer'), ('location_saisonniere', 'Louer en saisonnier')], max_length=20)),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('villa', 'Villa')], max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_moyen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('superficie_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('vente', 'Vendre'), ('location', 'Louer'), ('location_saisonniere', 'Louer en saisonnier')], max_length=20)),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('villa', 'Villa')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], default='brouillon', max_length=20)),
                ('disponible_immediatement', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nom_annonceur', models.CharField(max_length=100)),
                ('telephone_annonceur', models.CharField(max_length=20)),
                ('email_annonceur', models.EmailField(max_length=254)),
                ('profil_annonceur', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('agence', 'Agence'), ('mandataire', 'Mandataire')], max_length=20)),
                ('affichage_public_coordonnees', models.BooleanField(default=False)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('nombre_contacts', models.PositiveIntegerField(default=0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_habitable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_chambres', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_salons', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_salles_bain', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_cuisines', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_balcons', models.PositiveIntegerField(blank=True, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, null=True)),
                ('annee_construction', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('etat_general', models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('bon', 'Bon'), ('a_renover', 'À rénover')], max_length=20, null=True)),
                ('meuble', models.BooleanField(default=False)),
                ('terrain_titre', models.BooleanField(blank=True, null=True)),
                ('viabilisation_eau', models.BooleanField(default=False)),
                ('viabilisation_electricite', models.BooleanField(default=False)),
                ('viabilisation_acces_route', models.BooleanField(default=False)),
                ('usage_prevu', models.CharField(blank=True, choices=[('habitation', 'Habitation'), ('commercial', 'Commercial'), ('agricole', 'Agricole')], max_length=20, null=True)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bien', to='max_app.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_caracteristique', models.CharField(choices=[('piscine', 'Piscine'), ('jardin', 'Jardin'), ('terrasse', 'Terrasse'), ('parking', 'Parking'), ('securite_gardien', 'Gardien'), ('securite_alarme', 'Alarme'), ('securite_videosurveillance', 'Vidéosurveillance'), ('climatisation', 'Climatisation'), ('ascenseur', 'Ascenseur'), ('groupe_electrogene', 'Groupe électrogène'), ('internet_fibre', 'Internet/Fibre optique'), ('accessibilite_pmr', 'Accessibilité PMR')], max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='max_app.bien')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='max_app.annonce')),
            ],
            options={
                'ordering': ['-date_contact'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], max_length=20)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_statut', to='max_app.annonce')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_complete', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lieu', to='max_app.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('fichier', models.ImageField(blank=True, null=True, upload_to='annonces/images/')),
                ('lien_youtube', models.URLField(blank=True, null=True)),
                ('fichier_video', models.FileField(blank=True, null=True, upload_to='annonces/videos/')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='max_app.annonce')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TagSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_cle', models.CharField(max_length=100)),
                ('poids', models.PositiveIntegerField(default=1)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_seo', to='max_app.annonce')),
            ],
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['type_transaction', 'type_bien'], name='max_app_ann_type_tr_e4474a_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['statut', 'date_creation'], name='max_app_ann_statut_e0abe1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristique',
            unique_together={('bien', 'type_caracteristique')},
        ),
        migrations.AlterUniqueTogether(
            name='tagseo',
            unique_together={('annonce', 'mot_cle')},
        ),
    ]
