# Generated by Django 5.2.4 on 2025-07-31 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
        migrations.CreateModel(
            name='AlerteRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('type_bien', models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('commercial', 'Commercial'), ('terrain', 'Terrain')], max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('surface_min', models.FloatField(blank=True, null=True)),
                ('nb_chambres_min', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_salles_bain_min', models.PositiveIntegerField(blank=True, null=True)),
                ('mots_cles', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rayon_km', models.PositiveIntegerField(blank=True, help_text='Rayon en kilomètres', null=True)),
                ('frequence', models.CharField(choices=[('quotidienne', 'Quotidienne'), ('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle')], default='hebdomadaire', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_notification', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de recherche',
                'verbose_name_plural': 'Alertes de recherche',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('commercial', 'Commercial'), ('terrain', 'Terrain')], max_length=20)),
                ('surface', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nb_chambres', models.PositiveIntegerField(blank=True, null=True)),
                ('nb_salles_bain', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('nom_agent', models.CharField(max_length=100)),
                ('telephone_agent', models.CharField(max_length=20)),
                ('email_agent', models.EmailField(max_length=254)),
                ('caracteristiques', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='max_app.lieu')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='max_app.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
    ]
